volumes:
  public_assets: {}

services:
  app:
    volumes:
      - public_assets:/var/www/public
    ports:
      - '8088:8088'
    restart: always

  webserver:
    volumes:
      - './docker/production/nginx/app.conf:/etc/nginx/conf.d/default.conf'
      - public_assets:/var/www/public:ro
    ports:
      - '80:80'
    restart: always