volumes:
  public_assets: {}
  nginx-logs: {}
  certbot-etc: {}
  perfumarte_fail2ban_data: {}

services:
  app:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
        target: builder
    volumes:
      - public_assets:/var/www/public
    ports:
      - '8088:8088'
    restart: always

  webserver:
    image: nginx:1.25.4-alpine
    container_name: perfumarte-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './docker/production/nginx:/etc/nginx/conf.d'
      - './certbot/conf:/etc/letsencrypt'
      - './certbot/www:/var/www/certbot'
      - public_assets:/var/www/public:ro
      - nginx-logs:/var/log/nginx
      - ./docker/production/nginx/entrypoint.sh:/usr/local/bin/nginx-entrypoint.sh:ro
    command: /bin/sh -c "chmod +x /usr/local/bin/nginx-entrypoint.sh && /usr/local/bin/nginx-entrypoint.sh"
    depends_on:
      - app

  volumes:
  public_assets: {}
  nginx-logs: {}
  certbot-etc: {}
  perfumarte_fail2ban_data: {}

services:
  app:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
        target: builder
    volumes:
      - public_assets:/var/www/public
    ports:
      - '8088:8088'
    restart: always

  webserver:
    image: nginx:1.25.4-alpine
    container_name: perfumarte-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './docker/production/nginx:/etc/nginx/conf.d'
      - './certbot/conf:/etc/letsencrypt'
      - './certbot/www:/var/www/certbot'
      - public_assets:/var/www/public:ro
      - nginx-logs:/var/log/nginx
    command: nginx -g "daemon off;"
    depends_on:
      - app

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: perfumarte-fail2ban
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - F2B_LOG_LEVEL=DEBUG
    volumes:
      - type: volume
        source: perfumarte_fail2ban_data
        target: /data
      - type: bind
        source: ./docker/production/fail2ban/data/jail.d
        target: /data/jail.d
        read_only: true
      - type: bind
        source: ./docker/production/fail2ban/data/filter.d
        target: /data/filter.d
        read_only: true
      - nginx-logs:/var/log/nginx:ro
    depends_on:
      - webserver