volumes:
  public_assets: {}
  nginx-logs: {}
  certbot-etc: {}

services:
  app:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
        target: builder
    volumes:
      - public_assets:/var/www/public
    networks:
        - prais-network
    restart: always

  webserver:
    image: nginx:1.25.4-alpine
    container_name: perfumarte-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './docker/production/nginx:/etc/nginx/conf.d'
      - './certbot/conf:/etc/letsencrypt'
      - './certbot/www:/var/www/certbot'
      - public_assets:/var/www/public:ro
      - nginx-logs:/var/log/nginx
    command: >
      /bin/sh -c "
        ./generate-dummy-certificate.sh &&
        nginx -g 'daemon off;'
      "
    networks:
        - prais-network
    depends_on:
      - app

  certbot:
    image: certbot/certbot:v2.10.0
    container_name: prais-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: ""
    command: >
      /bin/sh -c "
        while :; do
          certbot renew --webroot --webroot-path=/var/www/certbot \
            --email jjorozco@unimonserrate.edu.co \
            -d www.prais.perfum-arte.com \
            --rsa-key-size 4096 \
            --agree-tos \
            --non-interactive;
          sleep 12h;
        done
      "
    networks:
      - prais-network
    depends_on:
      - webserver

  reverb:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
        target: builder
    entrypoint: ["/usr/local/bin/php", "artisan", "reverb:start", "--host=0.0.0.0", "--port=8088"]
    ports:
        - "${REVERB_PORT_EXT:-8088}:${REVERB_PORT:-8088}"
    volumes:
        - '.:/var/www'
    networks:
        - prais-network
    depends_on:
        - app

networks:
    prais-network:
        driver: bridge