services:
    webserver:
        image: 'nginx:stable-alpine'
        ports:
            - '${PROJECTPORT}:80'
        volumes:
            - './docker/${APP_ENV}/nginx/app.conf:/etc/nginx/conf.d/default.conf'
            - '.:/var/www'
        networks:
            - prais-network
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: builder
        entrypoint: /var/www/docker/entrypoint.sh
        ports:
            - '5173:5173'
            - '9000:9000'
            - '8088:8088'
        volumes:
            - '.:/var/www'
        networks:
            - prais-network
        command: php-fpm
networks:
    prais-network:
        driver: bridge