services:
    webserver:
        image: nginx:stable-alpine
        ports:
            - "${PROJECTPORT}:80"
        volumes:
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        ports:
            - "5173:5173"
            - "9000:9000"
        volumes:
            - .:/var/www
        networks:
            - app-network
        command: php-fpm

networks:
    app-network:
        driver: bridge