services:
    webserver:
        image: 'nginx:stable-alpine'
        ports:
            - '${PROJECTPORT}:80'
        volumes:
            - './docker/${APP_ENV}/nginx/app.conf:/etc/nginx/conf.d/default.conf'
            - './docker/production/ssl:/etc/ssl_aws'
            - '.:/var/www'
        networks:
            - prais-network
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: builder
        entrypoint: /usr/local/bin/entrypoint.sh
        ports:
            - '5173:5173'
            - '9000:9000'
        volumes:
            - '.:/var/www'
        networks:
            - prais-network
        command: php-fpm
    reverb:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: builder
        entrypoint: ["/usr/local/bin/php", "artisan", "reverb:start", "--host=0.0.0.0", "--port=8088"]
        ports:
            - "${REVERB_PORT_EXT:-8088}:${REVERB_PORT:-8088}"
        volumes:
            - '.:/var/www'
        networks:
            - prais-network
        depends_on:
            - app
networks:
    prais-network:
        driver: bridge